import { BN } from "@coral-xyz/anchor";
import type { Wallet } from "@coral-xyz/anchor";
import { PythSolanaReceiver } from "@pythnetwork/pyth-solana-receiver";
import {
  PublicKey,
  Transaction,
  VersionedTransaction,
  type Signer,
} from "@solana/web3.js";
import {
  ASSOCIATED_TOKEN_PROGRAM_ID,
  TOKEN_2022_PROGRAM_ID,
  getAssociatedTokenAddressSync,
} from "@solana/spl-token";
import { SystemProgram } from "@solana/web3.js";

import { SOL_USD_FEED_ID } from "./config";
import { connection } from "./connection";
import { PRESALE_CONFIG_PDA, TREASURY_PDA } from "./pdas";
import { buildProgramForWallet } from "./program";
import { fetchLatestSolPriceUpdate } from "./pyth";

export interface BuyTxBundle {
  /** Versioned transactions to send in order. Ephemeral signers have already applied. */
  transactions: VersionedTransaction[];
}

/**
 * Minimal wallet shim for `PythSolanaReceiver`. We only need `publicKey` — the
 * receiver library never calls `signTransaction` here because we use the
 * lower-level `buildVersionedTransactions` API and do signing ourselves.
 */
function makeWalletShim(publicKey: PublicKey): Wallet {
  return {
    publicKey,
    // These are never invoked during `buildVersionedTransactions`.
    signTransaction: async <T extends Transaction | VersionedTransaction>(
      tx: T
    ) => tx,
    signAllTransactions: async <T extends Transaction | VersionedTransaction>(
      txs: T[]
    ) => txs,
    payer: undefined as unknown as Wallet["payer"],
  };
}

/**
 * Build the versioned transaction(s) required to execute a LUVIA buy for the
 * connected wallet. The first tx (usually the only one) contains:
 *
 *   1. Compute-budget / price-update post instructions generated by Pyth.
 *   2. Our `luvia_presale.buy_tokens(solLamports)` instruction referencing the
 *      freshly-posted price-update account.
 *
 * Any ephemeral keypair required by the Pyth receiver (e.g. the price update
 * account itself) is already applied as a partial signature, so the caller
 * only needs to have the buyer wallet sign and send.
 */
export async function buildBuyTokensTransactions(params: {
  buyer: PublicKey;
  solLamports: bigint;
  tokenMint: PublicKey;
}): Promise<BuyTxBundle> {
  const { buyer, solLamports, tokenMint } = params;

  const walletShim = makeWalletShim(buyer);
  const program = buildProgramForWallet(walletShim);

  const priceUpdates = await fetchLatestSolPriceUpdate();

  const receiver = new PythSolanaReceiver({
    connection,
    wallet: walletShim,
  });

  const builder = receiver.newTransactionBuilder({
    closeUpdateAccounts: true,
  });

  await builder.addPostPriceUpdates(priceUpdates);

  const vault = getAssociatedTokenAddressSync(
    tokenMint,
    PRESALE_CONFIG_PDA,
    true,
    TOKEN_2022_PROGRAM_ID,
    ASSOCIATED_TOKEN_PROGRAM_ID
  );
  const buyerTokenAccount = getAssociatedTokenAddressSync(
    tokenMint,
    buyer,
    false,
    TOKEN_2022_PROGRAM_ID,
    ASSOCIATED_TOKEN_PROGRAM_ID
  );

  await builder.addPriceConsumerInstructions(async (getPriceUpdateAccount) => {
    const pythPriceUpdate = getPriceUpdateAccount(SOL_USD_FEED_ID);
    const ix = await program.methods
      .buyTokens(new BN(solLamports.toString()))
      .accountsStrict({
        buyer,
        presaleConfig: PRESALE_CONFIG_PDA,
        treasury: TREASURY_PDA,
        tokenMint,
        tokenVault: vault,
        buyerTokenAccount,
        pythPriceUpdate,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
        associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .instruction();
    return [{ instruction: ix, signers: [] }];
  });

  const built = await builder.buildVersionedTransactions({
    computeUnitPriceMicroLamports: 50_000,
  });

  // Partial-sign with every ephemeral keypair the Pyth receiver needs.
  const transactions: VersionedTransaction[] = built.map(
    ({ tx, signers }: { tx: VersionedTransaction; signers: Signer[] }) => {
      if (signers.length > 0) tx.sign(signers);
      return tx;
    }
  );

  return { transactions };
}
